#!/usr/bin/env ruby

# Opscode cookbooks.
site 'http://community.opscode.com/api/v1'
cookbook 'apt'
cookbook 'git'
cookbook 'java'
cookbook 'yum'

# Third-party cookbooks.
cookbook 'jenkins',
    :git => 'https://github.com/fnichol/chef-jenkins'

# Local cookbooks.
cookbook 'zenosslabs',
    :path => 'cookbooks-sources/zenosslabs'
