#!/bin/sh
echo "Uploading Custom Cookbooks"
echo "-------------------------------------------------------------------------"
knife cookbook upload zenosslabs

echo

echo "Uploading Custom Roles"
echo "-------------------------------------------------------------------------"
find cookbooks/zenosslabs/roles -name \*.rb | xargs -n1 knife role from file
