Vagrant::Config.run do |config|
    config.vm.box = 'CentOS-5.7-x86_64'
    config.vm.host_name = '321-centos5-x86_64.zenosslabs.com'

    config.vm.customize do |vm|
        vm.name = config.vm.host_name
        vm.memory_size = 1024
    end

    config.vm.network("192.168.57.101")

    config.ssh.max_tries = 150

    config.vm.provision :chef_solo do |chef|
        chef.cookbooks_path = "../../chef-repo/cookbooks"
        chef.add_recipe("zenosslabs::build-slave")

        chef.json = {
            :zenoss_rpm => 'zenoss-3.2.1.el5.x86_64.rpm',
            :zenoss_core_zenpacks_rpm => 'zenoss-core-zenpacks-3.2.1-1326.el5.x86_64.rpm',
            :zenoss_enterprise_zenpacks_rpm => 'zenoss-enterprise-zenpacks-3.2.1-1326.el5.x86_64.rpm'
        }
    end
end
