Vagrant::Config.run do |config|
    config.vm.box = 'ubuntu-10.04.3-server-amd64'
    config.vm.host_name = 'master.zenosslabs.com'

    config.vm.customize do |vm|
        vm.name = config.vm.host_name
        vm.memory_size = 512
    end

    config.vm.network("192.168.57.21")

    config.ssh.max_tries = 150

    config.vm.provision :chef_solo do |chef|
        chef.cookbooks_path = "../../chef-repo/cookbooks"
        chef.add_recipe("zenosslabs::jenkins-server")
    end
end
